name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Publish
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        dotnet-version: ["7.0.x"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore PoliAuthInstaller.sln

      - name: Build
        run: dotnet build --configuration Release --no-restore PoliAuthInstaller.sln

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./publish PoliAuthInstaller.sln

      - name: Create Artifact
        run: |
          mkdir artifacts
          tar -czvf artifacts/${{ matrix.os }}.tar.gz -C ./publish .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: ./artifacts/${{ matrix.os }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./artifacts

      - name: Create Release
        run: |
          TAG_NAME=${{ github.ref }}
          gh release create $TAG_NAME \
          ./artifacts/* \
          --title "Release $TAG_NAME" \
          --notes "New release of the project. Please find the artifacts attached below."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
