name: Release Pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Restore dependencies
        run: dotnet restore PoliAuthInstaller.sln

      - name: Build and Package
        run: |
          dotnet build --configuration Release PoliAuthInstaller.sln
          dotnet publish --configuration Release --output ./artifacts PoliAuthInstaller.sln

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-artifacts
          path: ./artifacts/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts/

      - name: Get Version from Tag
        id: version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: Release notes for ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
