name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Publish
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        dotnet-version: ["7.0.x"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore PoliAuthInstaller.sln

      - name: Build
        run: dotnet build --configuration Release --no-restore PoliAuthInstaller.sln

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./publish PoliAuthInstaller.sln

      - name: Create Artifact
        run: |
          mkdir artifacts
          tar -czvf artifacts/${{ matrix.os }}.tar.gz -C ./publish .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: ./artifacts/${{ matrix.os }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            New release of the project.
            Please find the artifacts attached below.

      - name: Upload Release Asset for Windows
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/windows-latest.tar.gz
          asset_name: windows-latest.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Asset for Linux
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/ubuntu-latest.tar.gz
          asset_name: ubuntu-latest.tar.gz
          asset_content_type: application/gzip
